forge "https://forgeapi.puppetlabs.com"

mod 'ringingliberty-chrony'
mod 'saz-resolv_conf'
mod 'CERNOps-motd'
mod 'rnelson0-hiera_resources'
mod 'puppetlabs-docker_platform'
mod 'rtyler-jenkins'
mod 'katello-pulp'
mod 'stahnma-epel'
mod 'puppetlabs-rabbitmq'
